### ISSUE TITLE
Boost compilation failed - numpy... missing binary operator before token "("

### ISSUE THREAD

**Issue by canonex** [LuxCoreRender/LinuxCompile#16]
Hi,
I'm on Debian testing and I'd like to compile LuxCore but I get multiple errors and the compilation process does not come to an end.

Thank you,
Riccardo

```

...
mv -f .deps/liblzma_la-lzma_encoder.Tpo .deps/liblzma_la-lzma_encoder.Plo
mv -f .deps/liblzma_la-lzma_encoder_optimum_normal.Tpo .deps/liblzma_la-lzma_encoder_optimum_normal.Plo
mv -f .deps/liblzma_la-lzma_decoder.Tpo .deps/liblzma_la-lzma_decoder.Plo
/bin/bash ../../libtool  --tag=CC   --mode=link gcc -fvisibility=hidden -Wall -Wextra -Wvla -Wformat=2 -Winit-self -Wmissing-include-dirs -Wstrict-aliasing -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wlogical-op -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -w -mtune=generic -mno-ssse3 -mmmx -msse -msse2 -O2 -pipe -mfpmath=sse -fPIC -no-undefined -version-info 5:5:0  -static-libgcc -static-libstdc++ -o liblzma.la -rpath /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib liblzma_la-tuklib_physmem.lo liblzma_la-common.lo liblzma_la-block_util.lo liblzma_la-easy_preset.lo liblzma_la-filter_common.lo liblzma_la-hardware_physmem.lo liblzma_la-index.lo liblzma_la-stream_flags_common.lo liblzma_la-vli_size.lo liblzma_la-alone_encoder.lo liblzma_la-block_buffer_encoder.lo liblzma_la-block_encoder.lo liblzma_la-block_header_encoder.lo liblzma_la-easy_buffer_encoder.lo liblzma_la-easy_encoder.lo liblzma_la-easy_encoder_memusage.lo liblzma_la-filter_buffer_encoder.lo liblzma_la-filter_encoder.lo liblzma_la-filter_flags_encoder.lo liblzma_la-index_encoder.lo liblzma_la-stream_buffer_encoder.lo liblzma_la-stream_encoder.lo liblzma_la-stream_flags_encoder.lo liblzma_la-vli_encoder.lo liblzma_la-alone_decoder.lo liblzma_la-auto_decoder.lo liblzma_la-block_buffer_decoder.lo liblzma_la-block_decoder.lo liblzma_la-block_header_decoder.lo liblzma_la-easy_decoder_memusage.lo liblzma_la-filter_buffer_decoder.lo liblzma_la-filter_decoder.lo liblzma_la-filter_flags_decoder.lo liblzma_la-index_decoder.lo liblzma_la-index_hash.lo liblzma_la-stream_buffer_decoder.lo liblzma_la-stream_decoder.lo liblzma_la-stream_flags_decoder.lo liblzma_la-vli_decoder.lo liblzma_la-check.lo  liblzma_la-crc32_table.lo  liblzma_la-crc32_fast.lo  liblzma_la-crc64_table.lo  liblzma_la-crc64_fast.lo liblzma_la-sha256.lo liblzma_la-lz_encoder.lo liblzma_la-lz_encoder_mf.lo liblzma_la-lz_decoder.lo  liblzma_la-lzma_encoder.lo liblzma_la-lzma_encoder_presets.lo liblzma_la-lzma_encoder_optimum_fast.lo liblzma_la-lzma_encoder_optimum_normal.lo liblzma_la-fastpos_table.lo liblzma_la-lzma_decoder.lo liblzma_la-lzma2_encoder.lo liblzma_la-lzma2_decoder.lo  liblzma_la-price_table.lo  liblzma_la-delta_common.lo liblzma_la-delta_encoder.lo liblzma_la-delta_decoder.lo liblzma_la-simple_coder.lo liblzma_la-simple_encoder.lo liblzma_la-simple_decoder.lo liblzma_la-x86.lo liblzma_la-powerpc.lo liblzma_la-ia64.lo liblzma_la-arm.lo liblzma_la-armthumb.lo liblzma_la-sparc.lo   
libtool: link: ar cru .libs/liblzma.a  liblzma_la-tuklib_physmem.o liblzma_la-common.o liblzma_la-block_util.o liblzma_la-easy_preset.o liblzma_la-filter_common.o liblzma_la-hardware_physmem.o liblzma_la-index.o liblzma_la-stream_flags_common.o liblzma_la-vli_size.o liblzma_la-alone_encoder.o liblzma_la-block_buffer_encoder.o liblzma_la-block_encoder.o liblzma_la-block_header_encoder.o liblzma_la-easy_buffer_encoder.o liblzma_la-easy_encoder.o liblzma_la-easy_encoder_memusage.o liblzma_la-filter_buffer_encoder.o liblzma_la-filter_encoder.o liblzma_la-filter_flags_encoder.o liblzma_la-index_encoder.o liblzma_la-stream_buffer_encoder.o liblzma_la-stream_encoder.o liblzma_la-stream_flags_encoder.o liblzma_la-vli_encoder.o liblzma_la-alone_decoder.o liblzma_la-auto_decoder.o liblzma_la-block_buffer_decoder.o liblzma_la-block_decoder.o liblzma_la-block_header_decoder.o liblzma_la-easy_decoder_memusage.o liblzma_la-filter_buffer_decoder.o liblzma_la-filter_decoder.o liblzma_la-filter_flags_decoder.o liblzma_la-index_decoder.o liblzma_la-index_hash.o liblzma_la-stream_buffer_decoder.o liblzma_la-stream_decoder.o liblzma_la-stream_flags_decoder.o liblzma_la-vli_decoder.o liblzma_la-check.o liblzma_la-crc32_table.o liblzma_la-crc32_fast.o liblzma_la-crc64_table.o liblzma_la-crc64_fast.o liblzma_la-sha256.o liblzma_la-lz_encoder.o liblzma_la-lz_encoder_mf.o liblzma_la-lz_decoder.o liblzma_la-lzma_encoder.o liblzma_la-lzma_encoder_presets.o liblzma_la-lzma_encoder_optimum_fast.o liblzma_la-lzma_encoder_optimum_normal.o liblzma_la-fastpos_table.o liblzma_la-lzma_decoder.o liblzma_la-lzma2_encoder.o liblzma_la-lzma2_decoder.o liblzma_la-price_table.o liblzma_la-delta_common.o liblzma_la-delta_encoder.o liblzma_la-delta_decoder.o liblzma_la-simple_coder.o liblzma_la-simple_encoder.o liblzma_la-simple_decoder.o liblzma_la-x86.o liblzma_la-powerpc.o liblzma_la-ia64.o liblzma_la-arm.o liblzma_la-armthumb.o liblzma_la-sparc.o
ar: 'u' modifier ignored since 'D' is the default (see 'U')
libtool: link: ranlib .libs/liblzma.a
libtool: link: ( cd ".libs" && rm -f "liblzma.la" && ln -s "../liblzma.la" "liblzma.la" )
make[4]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
Making all in xzdec
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[3]: Nessuna operazione da eseguire per «all».
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src»
make[3]: Nessuna operazione da eseguire per «all-am».
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src»
Making all in po
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/po»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/po»
Making all in tests
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/tests»
make[2]: Nessuna operazione da eseguire per «all».
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/tests»
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5»
make[1]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5»
Making install in src
make[1]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src»
Making install in liblzma
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
Making install in api
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/liblzma/api»
make[4]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/liblzma/api»
make[4]: Nessuna operazione da eseguire per «install-exec-am».
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/include'
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/include/lzma'
 /usr/bin/install -c -m 644  lzma/base.h lzma/bcj.h lzma/block.h lzma/check.h lzma/container.h lzma/delta.h lzma/filter.h lzma/hardware.h lzma/index.h lzma/index_hash.h lzma/lzma.h lzma/stream_flags.h lzma/version.h lzma/vli.h '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/include/lzma'
 /usr/bin/install -c -m 644  lzma.h '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/include/.'
make[4]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma/api»
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma/api»
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
make[4]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   liblzma.la '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib'
libtool: install: /usr/bin/install -c .libs/liblzma.lai /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/liblzma.la
libtool: install: /usr/bin/install -c .libs/liblzma.a /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/liblzma.a
libtool: install: chmod 644 /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/liblzma.a
libtool: install: ranlib /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/liblzma.a
libtool: finish: PATH="/home/crickyx/.local/bin:~/.local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin" ldconfig -n /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/pkgconfig'
 /usr/bin/install -c -m 644 liblzma.pc '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/lib/pkgconfig'
make[4]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/liblzma»
Making install in xzdec
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/bin'
make  install-data-hook
make[4]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[4]: Nessuna operazione da eseguire per «install-data-hook».
make[4]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src/xzdec»
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src»
make[3]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/src»
make[3]: Nessuna operazione da eseguire per «install-exec-am».
make[3]: Nessuna operazione da eseguire per «install-data-am».
make[3]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src»
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src»
make[1]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/src»
Making install in po
make[1]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/po»
installing cs.gmo as /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/locale/cs/LC_MESSAGES/xz.mo
installing de.gmo as /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/locale/de/LC_MESSAGES/xz.mo
installing fr.gmo as /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/locale/fr/LC_MESSAGES/xz.mo
installing it.gmo as /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/locale/it/LC_MESSAGES/xz.mo
installing pl.gmo as /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/locale/pl/LC_MESSAGES/xz.mo
if test "xz" = "gettext-tools"; then \
  /usr/bin/mkdir -p /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/gettext/po; \
  for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
    /usr/bin/install -c -m 644 ./$file \
		    /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/gettext/po/$file; \
  done; \
  for file in Makevars; do \
    rm -f /home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/gettext/po/$file; \
  done; \
else \
  : ; \
fi
make[1]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/po»
Making install in tests
make[1]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/tests»
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5/tests»
make[2]: Nessuna operazione da eseguire per «install-exec-am».
make[2]: Nessuna operazione da eseguire per «install-data-am».
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/tests»
make[1]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5/tests»
make[1]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5»
make[2]: ingresso nella directory «/tmp/luxbuild/xz-5.0.5»
make[2]: Nessuna operazione da eseguire per «install-exec-am».
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz'
 /usr/bin/install -c -m 644 AUTHORS COPYING COPYING.GPLv2 NEWS README THANKS TODO doc/faq.txt doc/history.txt doc/xz-file-format.txt doc/lzma-file-format.txt '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz'
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz/examples'
 /usr/bin/install -c -m 644 doc/examples/00_README.txt doc/examples/01_compress_easy.c doc/examples/02_decompress.c doc/examples/03_compress_custom.c doc/examples/Makefile '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz/examples'
 /usr/bin/mkdir -p '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz/examples_old'
 /usr/bin/install -c -m 644 doc/examples_old/xz_pipe_comp.c doc/examples_old/xz_pipe_decomp.c '/home/crickyx/Programmi/LuxCore-LinuxCompile/target-64-sse2/share/doc/xz/examples_old'
make[2]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5»
make[1]: uscita dalla directory «/tmp/luxbuild/xz-5.0.5»
 * lzma compiled and installed successfully
 * Cleaning and unpacking boost
 * Compiling boost
 * Patching Boost Python support
patching file libs/python/src/exec.cpp
 * Compiling boost for python-3.10
Building Boost.Build engine with toolset gcc... tools/build/src/engine/b2
Detecting Python version... 3.10
Unicode/ICU support for Boost.Regex?... disabled.
Generating Boost.Build configuration in project-config.jam for gcc...

Bootstrapping is done. To build, run:

    ./b2
    
To generate header files, run:

    ./b2 headers

To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/

notice: found boost-build.jam at /tmp/luxbuild/boost_1_72_0/boost-build.jam
notice: loading Boost.Build from /tmp/luxbuild/boost_1_72_0/tools/build/src
notice: Searching '/etc' '/home/crickyx' '/tmp/luxbuild/boost_1_72_0/tools/build/src' '/usr/share/boost-build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/kernel' '/tmp/luxbuild/boost_1_72_0/tools/build/src/util' '/tmp/luxbuild/boost_1_72_0/tools/build/src/build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/tools' '/tmp/luxbuild/boost_1_72_0/tools/build/src/contrib' '/tmp/luxbuild/boost_1_72_0/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in '/etc' '/home/crickyx' '/tmp/luxbuild/boost_1_72_0/tools/build/src' '/usr/share/boost-build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/kernel' '/tmp/luxbuild/boost_1_72_0/tools/build/src/util' '/tmp/luxbuild/boost_1_72_0/tools/build/src/build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/tools' '/tmp/luxbuild/boost_1_72_0/tools/build/src/contrib' '/tmp/luxbuild/boost_1_72_0/tools/build/src/.'.
notice: Searching '/home/crickyx' '/tmp/luxbuild/boost_1_72_0/tools/build/src' '/usr/share/boost-build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/kernel' '/tmp/luxbuild/boost_1_72_0/tools/build/src/util' '/tmp/luxbuild/boost_1_72_0/tools/build/src/build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/tools' '/tmp/luxbuild/boost_1_72_0/tools/build/src/contrib' '/tmp/luxbuild/boost_1_72_0/tools/build/src/.' for user-config configuration file 'user-config.jam'.
notice: Configuration file 'user-config.jam' not found in '/home/crickyx' '/tmp/luxbuild/boost_1_72_0/tools/build/src' '/usr/share/boost-build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/kernel' '/tmp/luxbuild/boost_1_72_0/tools/build/src/util' '/tmp/luxbuild/boost_1_72_0/tools/build/src/build' '/tmp/luxbuild/boost_1_72_0/tools/build/src/tools' '/tmp/luxbuild/boost_1_72_0/tools/build/src/contrib' '/tmp/luxbuild/boost_1_72_0/tools/build/src/.'.
notice: Searching '.' for project-config configuration file 'project-config.jam'.
notice: Loading project-config configuration file 'project-config.jam' from '.'.
notice: will use 'g++' for gcc, condition <toolset>gcc-12
notice: using gcc libraries :: <toolset>gcc-12 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-12 :: /usr/bin/ar
notice: using gcc ranlib :: <toolset>gcc-12 :: /usr/bin/ranlib
warning: toolset gcc initialization: can not find tool windres
warning: initialized from project-config.jam:12
notice: using rc compiler :: <toolset>gcc-12 :: /usr/bin/as
notice: [python-cfg] Configuring python...
notice: [python-cfg]   user-specified version: "3.10"
notice: [python-cfg]   user-specified cmd-or-prefix: "/usr"
notice: [python-cfg] Checking interpreter command "/usr/bin/python3.10"...
notice: [python-cfg] running command '/usr/bin/python3.10 -c "from sys import *; print('version=%d.%d\nplatform=%s\nprefix=%s\nexec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "/usr/bin/python3.10"
notice: [python-cfg]   include path: "/usr/include/python3.10"
notice: [python-cfg]   library path: "/usr/lib/python3.10/config" "/usr/lib"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command '/usr/bin/python3.10 -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy disabled. Reason:
notice: [python-cfg]   /usr/bin/python3.10 -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())" aborted with 
notice: [python-cfg]   Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/usr/bin/python3.10"
  * The NumPy version is: "1.24.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
notice: [cmdline-cfg] adding toolset=gcc to the build request.
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
notice: [lzma] Using pre-installed library
notice: [lzma] Condition
notice: [zstd] Using pre-installed library
notice: [zstd] Condition
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
    - zlib                     : yes
    - bzip2                    : no
    - lzma                     : yes
    - zstd                     : yes
    - lzma                     : yes
    - has_lzma_cputhreads builds : yes
    - iconv (libc)             : yes
    - icu                      : yes
    - lockfree boost::atomic_flag : yes
    - has_icu builds           : yes

Component configuration:

    - atomic                   : not building
    - chrono                   : building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : building
    - locale                   : building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : building
    - python                   : building
    - random                   : not building
    - regex                    : building
    - serialization            : building
    - stacktrace               : not building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

In file included from /usr/include/pthread.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr.h:148,
                 from /usr/include/c++/12/ext/atomicity.h:35,
                 from /usr/include/c++/12/bits/ios_base.h:39,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/ostream:38,
                 from ./boost/system/error_code.hpp:17,
                 from ./boost/system/system_error.hpp:11,
                 from ./boost/thread/exceptions.hpp:22,
                 from ./boost/thread/pthread/thread_data.hpp:10,
                 from ./boost/thread/thread_only.hpp:17,
                 from libs/thread/src/pthread/thread.cpp:11:
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/pthread.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr.h:148,
                 from /usr/include/c++/12/ext/atomicity.h:35,
                 from /usr/include/c++/12/bits/locale_classes.h:41,
                 from /usr/include/c++/12/locale:39,
                 from ./boost/locale/collator.hpp:16,
                 from libs/locale/src/icu/collator.cpp:9:
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/pthread.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr.h:148,
                 from /usr/include/c++/12/ext/atomicity.h:35,
                 from /usr/include/c++/12/bits/locale_classes.h:41,
                 from /usr/include/c++/12/locale:39,
                 from ./boost/locale/date_time_facet.hpp:18,
                 from libs/locale/src/icu/date_time.cpp:9:
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/pthread.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr.h:148,
                 from /usr/include/c++/12/ext/atomicity.h:35,
                 from /usr/include/c++/12/bits/ios_base.h:39,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/ostream:38,
                 from ./boost/locale/formatting.hpp:18,
                 from libs/locale/src/icu/formatter.cpp:9:
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~
In file included from /usr/include/pthread.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:35,
                 from /usr/include/x86_64-linux-gnu/c++/12/bits/gthr.h:148,
                 from /usr/include/c++/12/ext/atomicity.h:35,
                 from /usr/include/c++/12/bits/locale_classes.h:41,
                 from /usr/include/c++/12/locale:39,
                 from libs/locale/src/icu/numeric.cpp:9:
./boost/thread/pthread/thread_data.hpp:60:5: error: missing binary operator before token "("
   60 | #if PTHREAD_STACK_MIN > 0
      |     ^~~~~~~~~~~~~~~~~
...failed updating 5 targets...
 !!! Boost compilation failed
```

**Comment by smogol66** [comment]
Hi,
I have the same problem, ubuntu 22.04 on a intel i5 without specialized graphic card.

BR 
smogol66

**Comment by techno-sam** [comment]
Related boost issue: boostorg/thread#364
Since fixed by: boostorg/thread#297
```diff
- #if PTHREAD_STACK_MIN > 0
+ #ifdef PTHREAD_STACK_MIN
```

Should be easily patchable. I'll be trying to get a Blender 4.2 (thus python 3.11) build working soon :tm:
I'll make a PR here once I get it working... should be fun sorting out Python dependency f***ery, seeing as I have numpy 2 installed on my machine. I wonder if it is (easily) possible to pull the relevant python and numpy include files for a venv.
